config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :task_schedules
  resources :users

  root to: 'users#index'
  get 'task_complete' => 'tasks#complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  def complete
  	self.completed ? "YES" : "NO"
  end
end

app/models/task_schedule.rb
class TaskSchedule < ApplicationRecord
  belongs_to :user
  scope :tasks_due_today, -> { where("DATE(due_date) = ?", Date.today) } 
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :task_schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/task_schedules_controller.rb
class TaskSchedulesController < ApplicationController
  before_action :set_task_schedule, only: [:show, :edit, :update, :destroy]

  # GET /task_schedules
  # GET /task_schedules.json
  def index
      @task_schedules = TaskSchedule.all
  end

  # GET /task_schedules/1
  # GET /task_schedules/1.json
  def show
  end

  # GET /task_schedules/new
  def new
    @task_schedule = TaskSchedule.new
  end

  # GET /task_schedules/1/edit
  def edit
  end

  # POST /task_schedules
  # POST /task_schedules.json
  def create
    @task_schedule = TaskSchedule.new(task_schedule_params)

    respond_to do |format|
      if @task_schedule.save
        format.html { redirect_to @task_schedule, notice: 'Task schedule was successfully created.' }
        format.json { render :show, status: :created, location: @task_schedule }
      else
        format.html { render :new }
        format.json { render json: @task_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_schedules/1
  # PATCH/PUT /task_schedules/1.json
  def update
    respond_to do |format|
      if @task_schedule.update(task_schedule_params)
        format.html { redirect_to @task_schedule, notice: 'Task schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_schedule }
      else
        format.html { render :edit }
        format.json { render json: @task_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_schedules/1
  # DELETE /task_schedules/1.json
  def destroy
    @task_schedule.destroy
    respond_to do |format|
      format.html { redirect_to task_schedules_url, notice: 'Task schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_schedule
      @task_schedule = TaskSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_schedule_params
      params.require(:task_schedule).permit(:name, :due_date, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def complete
    # logger.debug "9999999999999999999#{params.inspect}"
    if params[:id]
      ts = TaskSchedule.find params[:id]
      @user = ts.user
      exists_task = Task.where(name: ts.name, user_id: ts.user.id)
      # logger.debug "-======= name: #{ts.name} : user_id: #{ts.user.id} #{exists_task.blank?}  #{exists_task.inspect}"
      if exists_task.blank?
        completed_task = Task.new
        completed_task.name = ts.name
        completed_task.completed = true
        completed_task.due_date = ts.due_date
        completed_task.user_id = ts.user_id
        completed_task.save
        render :complete
      else
        render :task_already_completed
      end
    else
      render :not_allow
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :completed, :due_date, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_schedules_helper.rb
module TaskSchedulesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

	def format_time(time, timezone)
	  time.in_time_zone(timezone)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task_schedules/_form.html.erb
<%= form_with(model: task_schedule, local: true) do |form| %>
  <% if task_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_schedule.errors.count, "error") %> prohibited this task_schedule from being saved:</h2>

      <ul>
      <% task_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_schedule_name %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.datetime_select :due_date, id: :task_schedule_due_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :task_schedule_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_schedules/_task_schedule.html.erb
<tr>
	<td>
		<%= task_schedule.id %>
	</td>
  <td>
    <%= task_schedule.name %>
  </td>
  <td>
    <%#= task_schedule.due_date %> 
    <%= format_time(task_schedule.due_date, task_schedule.user.time_zone) %> ( 
    <%= task_schedule.user.time_zone %>)
    <%#= format_time(task_schedule.due_date, 'Eastern Time (US & Canada)') %>
  </td>
  <td>
  	<%= link_to "complete" , task_complete_path(id: task_schedule.id), remote: true ,class: "btn btn-primary"%>
  </td>
</tr>

app/views/task_schedules/edit.html.erb
<h1>Editing Task Schedule</h1>

<%= render 'form', task_schedule: @task_schedule %>

<%= link_to 'Show', @task_schedule %> |
<%= link_to 'Back', task_schedules_path %>

app/views/task_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Due date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_schedules.each do |task_schedule| %>
      <tr>
        <td><%= task_schedule.name %></td>
        <td><%= task_schedule.due_date %></td>
        <td><%= task_schedule.user %></td>
        <td><%= link_to 'Show', task_schedule %></td>
        <td><%= link_to 'Edit', edit_task_schedule_path(task_schedule) %></td>
        <td><%= link_to 'Destroy', task_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Schedule', new_task_schedule_path %>

app/views/task_schedules/new.html.erb
<h1>New Task Schedule</h1>

<%= render 'form', task_schedule: @task_schedule %>

<%= link_to 'Back', task_schedules_path %>

app/views/task_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_schedule.name %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task_schedule.due_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @task_schedule.user %>
</p>

<%= link_to 'Edit', edit_task_schedule_path(@task_schedule) %> |
<%= link_to 'Back', task_schedules_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed, id: :task_completed %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.datetime_select :due_date, id: :task_due_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :task_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
	<td>
		<%= task.id %>
  <td>
    <%= task.name %>
  </td>
  <td>
    <%= task.complete %>
  </td>
  <td>
    <%= task.due_date %>
  </td>
</tr>

app/views/tasks/_tasks.html.erb
<tr>
  <td>
    <%= task.name %>
  </td>
  <td>
    <%= task.complete %>
  </td>
  <td>
    <%= task.due_date %>
  </td>
</tr>

app/views/tasks/complete.js.erb
$(document).ready(function(){
    console.log( "ready! <%= params.inspect %>" );
    $("#user_tasks").html("<%= j render @user.tasks %>")
});

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Completed</th>
      <th>Due date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.completed %></td>
        <td><%= task.due_date %></td>
        <td><%= task.user %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/not_allow.js.erb
$(document).ready(function(){
    console.log( "not allow without ID" );
    alert ("not allow without ID");
});

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/task_already_completed.js.erb
$(document).ready(function(){
    console.log( "already completed" );
    alert("Task already completed!");
});

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>User Time Zone:</strong>
  <%= @user.time_zone %>
</p>
<p>
  <strong>Show tasks due TODAY</strong>
  <%= link_to 'Tasks Due Today', user_path(@user, today: 'Yes')%> | <%= link_to 'Show All Tasks', @user%> 
</p>
<p>
  <strong>Task Schedules</strong>
  <table>
      <thead>
        <th>
          ID
        </th>
        <th>
          Name
        </th>
        <th>
          Due Date
        </th>
        <th>
          Complete
        </th>
      </thead>
      <tbody>
          <% if params[:today] %>
            <% if @user.task_schedules.tasks_due_today.size == 0 %>
              <tr><td><strong>No task is due today</strong></td></tr>
            <% else %>
              <%= render @user.task_schedules.tasks_due_today %>
            <% end %>
          <% else %>
            <%= render @user.task_schedules %>
          <% end %>
      </tbody>
  </table>
</p>

<p>
  <strong>Tasks</strong>
  <table>
      <thead>
        <th>
          ID
        </th>
        <th>
          Name
        </th>
        <th>
          Complete
        </th>
        <th>
          Due Date
        </th>
      </thead>
      <tbody id="user_tasks">
          <%= render @user.tasks %>
      </tbody>
      </div>  
  </table>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>